"""Local bidirect-GP run — AUTO-GENERATED by utils/local_calibrate.sh.

LOCAL ONLY — DO NOT RUN ON AWS as-is. The request path is "/" because the
locally-launched uwsgi container exposes the workload on root (its
/function/graph_mst route is commented in the source). On AWS the path
"/function/graph_mst" works through a different routing path.

Calibrated for this machine (manual override applied):
  Docker vCPU       = 8
  μ_eff/core        = 17.3 (c≤4) | 13.7 (c=8, VM saturating)   (M/M/c fit)
  init_cores        = 4   (manual: gives PPO room to scale up)
  max_cores         = 8   (physical Docker VM cap)
  lam               = 50  (manual: ρ_pre at c=4 ≈ 0.74 → marginal SLA → PPO must scale)
  capacity at c=8   = 110 req/s; ρ at lam=50, c=8 = 0.46 (well under SLA)
  drift onset       → ρ_post at c=4 ≈ 0.96 (saturating but not imploding)

Hypothesis under test: H4 — GP training buffer is poisoned by a pre+post-drift
mix, leading to a degenerate fit that fails to extrapolate post-drift OOD.
With `gp_buffer_reset_at = noise_start` we wipe the buffer at the known drift
onset, giving the GP a clean post-drift-only training set.

If H4 is the dominant cause, the post-drift cascade observed at t≈300-365 in
the AWS bidirect run should disappear and tail latency should drop toward the
PPO baseline level.
"""

CONFIG = {
    "hosts": ["http://localhost:8080", "http://localhost:8081"],
    "containerIds": ["graph_set", "graph_quota"],
    "request": {
        "method": "POST",
        "data": {"size": 25000},
        "headers": {"Content-Type": "application/json"},
        # LOCAL: workload exposed on  (no OpenFaaS gateway here).
        "path": "/",
    },
    "cpu_range_start": 0,
    "monitoring_window": 30,
    "app_sla": 0.25,
    "wait_time_min": 1,
    "wait_time_max": 1,
    "spawn_rate": 1,

    "end": 600,

    # Drift: step at t=300, persistent until end.
    "noise_start": 300,
    "noise_scale": 1.3,
    "noise_type": "avg",
    "noise_drift_kind": "step",
    "noise_drift_end": 600,
    "noise_drift_period": 300,
    "seed": 42,

    "generator": {
        "class": "StationaryGen",
        "params": {"lam": 50},
    },

    "controller": {
        "class": "GPPPOController",
        "params": {
            "period": 1,
            "init_cores": 4,
            "min_cores": 1.0,
            "max_cores": 8,
            "st": 1.0,
            "st_max": 1.0,
            "min_st": 1.0,
            "train": False,
            "deterministic_eval": True,
            "burst_mode": "none",
            "trend_features": False,
            "enable_log": True,
            "log_dir": "./logs",

            # PI muted — guardrail is GP-only
            "bc": 0.0,
            "dc": 0.0,
            "pi_anti_windup": False,
            "pi_e_clip": 10.0,
            "pi_error_form": "linear",
            "pi_rt_deadband_frac": 0.30,

            # GP scheduling
            "gp_train_start": 10,
            "gp_min_samples": 30,
            "gp_train_freq": 50,
            "gp_max_buffer_size": 500,
            "pi_start_time": 5,
            "gp_time_period": 200,
            "gp_async": True,

            # B1: bidirectional guardrail
            "gp_target_mode": "signed_shortfall",
            "gp_percentile": 50,
            "gp_normalize_inputs": True,
            "gp_trust_mode": "outcome",
            "gp_distrust_dwell": 0,

            # Lookahead disabled in signed mode
            "gp_lookahead_horizon": 0,
            "gp_adaptive_train": False,
            "gp_drift_threshold": 1.5,
            "gp_min_train_interval": 10,
            "gp_eviction_keep": 0,

            # H4 in-vitro — hard-reset GP at known drift onset
            "gp_buffer_reset_at": 300,
        },
    },
}


EXP_NAME = __file__.split("/")[-1].split(".")[0]

from base_experiment import *
setup(EXP_NAME, CONFIG)
